# These are supported funding model platforms

patreon: kevinfaguiar
ko_fi: kevinfaveri
liberapay: kevinfaguiar
custom: ["https://cutt.ly/kevin-paypal", "https://www.blockchain.com/pt/btc/address/bc1q3ln0v73ketq3fzeh2saa2tsew4xmrwepdj42jw", "https://pag.ae/7W8bEJKYK", "https://picpay.me/kevinfguiar"]
