name: Docs - Build and Deploy
on:
  push:
    paths:
      - "docs/**"
    branches:    
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: kevinfaguiar/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        BUILD_DIR: docs/.vuepress/dist
        BUILD_SCRIPT: yarn install && yarn docs:build
